#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo 'Holberton School' | sudo tee /var/www/html/index.html
service nginx start
sudo chmod -R 777 /etc/nginx
default="/etc/nginx/sites-enabled/default"
location="location /redirect_me {rewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;}"
sudo sed -i "30i $location" "$default"
sudo service nginx restart
