#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM signal

file=/var/run/holbertonscript.pid
echo $$ >> $file

trap "echo 'Y U no love me?!'; exit 0; rm $file" SIGINT
trap "echo 'I hate the kill command'; exit 0; rm $file" SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2
done
